version: '2'
services:

######### opentsdb service
  opentsdb:
    build:
      context: ./opentsdb
      dockerfile: Dockerfile.oraclejdk-8
    image: opentsdb
    depends_on:
      - opentsdb_hbase_standalone
    ports:
      - '4242:4242'
    container_name: opentsdb
    environment:
      TIMEZONE: Asia/Bangkok
      HBASE_ZOOKEEPER_QUORUM: 'opentsdb_hbase_standalone:2181'
    volumes_from:
      - opentsdb_hbase_standalone

  opentsdb_hbase_standalone:
    build:
      context: ./hbase
      dockerfile: Dockerfile.oraclejdk-8
    image: 'hbase:1.2.6'
    ports:
      - '2181:2181'
      - '16000:16000'
      - '16010:16010'
      - '16201:16201'
      - '16301:16301'
    environment:
      TIMEZONE: Asia/Bangkok
      HBASE_ZOOKEEPER_QUORUM: 'opentsdb_hbase_standalone:2181'

######### tscache service

  tscache:
    build:
      context: ./opentsdb
      dockerfile: Dockerfile.oraclejdk-8.test
    image: 'opentsdb:2.3-tscache'
    depends_on:
      - tscache_hbase_standalone
      - memcached
    ports:
      - '4243:4242'
    expose:
      - 4243
    container_name: tscache
    environment:
      TIMEZONE: Asia/Bangkok
      HBASE_ZOOKEEPER_QUORUM: 'tscache_hbase_standalone:2182'
      HBASE_HOME: /opt/hbase
    volumes_from:
      - tscache_hbase_standalone
    volumes:
      - /home/mildronize/opentsdb:/opt/opentsdb/opentsdb-2.3.0


  tscache_hbase_standalone:
    build:
      context: ./hbase
      dockerfile: Dockerfile.oraclejdk-8
    image: 'hbase:1.2.6'
    ports:
      - '2182:2181'
      - '16001:16000'
      - '16011:16010'
      - '16202:16201'
      - '16302:16301'
    environment:
      TIMEZONE: Asia/Bangkok
      HBASE_ZOOKEEPER_QUORUM: 'tscache_hbase_standalone:2182'

  memcached:
    image: 'memcached:1.5-alpine'
    ports:
      - '11211:11211'
    command: memcached -vv

