version: '2'
services:
  hbase_standalone:
    build: hbase/
    image: hbase:1.2.4
    ports:
      - 2181:2181
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    # volumes:
        # - /home/mildronize/tmp/hbase:/data/hbase
    container_name: hbase
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181

  tsdb:
    build: ./opentsdb
    image: opentsdb
    depends_on:
        - hbase_standalone
    ports:
        - 4242:4242
    container_name: tsdb
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181
    volumes_from:
        - hbase_standalone

  tsdb-dev:
    build:
      context: ./opentsdb
      dockerfile: Dockerfile.dev

    image: opentsdb:2.3-dev
    depends_on:
        - hbase_standalone
        - rabbit
    ports:
        - 4242:4242
    expose:
        - 4242
    container_name: tsdb
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181
        HBASE_HOME: /opt/hbase
    volumes_from:
        - hbase_standalone
        - unison
    # volumes:
    #     - ./opentsdb/dev:/home/dev/opentsdb-dev
  rabbit:
    image: rabbitmq:3-alpine


  unison:  
      image: leighmcculloch/unison:latest  
      environment:  
          - UNISON_WORKING_DIR=/home/dev/opentsdb-dev/opentsdb
      volumes:
          - /home/dev/opentsdb-dev/opentsdb
      ports:  
          - "5000:5000"
