version: '2'
services:
  hbase_standalone:
    build: hbase/
    image: hbase:1.2.4
    ports:
      - 2181:2181
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    # volumes:
        # - /home/mildronize/tmp/hbase:/data/hbase
    container_name: hbase
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181

  tsdb:
    build: ./opentsdb
    image: opentsdb
    depends_on:
        - hbase_standalone
    ports:
        - 4242:4242
    container_name: tsdb
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181
    volumes_from:
        - hbase_standalone

  tsdb-dev:
    build:
      context: ./opentsdb
      dockerfile: Dockerfile.test

    image: opentsdb:2.3-test
    depends_on:
        - hbase_standalone
        - rabbit
    ports:
        - 4242:4242
    expose:
        - 4242
    container_name: tsdb
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181
        HBASE_HOME: /opt/hbase
    volumes_from:
        - hbase_standalone
        - unison
    # volumes:
    #     - ./opentsdb/dev:/home/dev/opentsdb-dev
  rabbit:
    image: rabbitmq:3-alpine
    ports:
        - 25672:25672
        - 4369:4369
        - 5671:5671
        - 5672:5672
    hostname: localhost

  unison:  
      image: leighmcculloch/unison:latest  
      environment:  
          - UNISON_WORKING_DIR=/opt/opentsdb/opentsdb-2.3.0
      volumes:
          - /opt/opentsdb/opentsdb-2.3.0
      ports:  
          - "5000:5000"

#   unison:  
#       image: leighmcculloch/unison:latest  
#       environment:  
#           - UNISON_WORKING_DIR=/home/dev/opentsdb-dev/opentsdb
#       volumes:
#           - /home/dev/opentsdb-dev/opentsdb
#       ports:  
#           - "5000:5000"

# tmp
#   tsdb-run:
#     build:
#       context: ./opentsdb
#       dockerfile: Dockerfile.test

#     image: opentsdb:2.3-run
#     depends_on:
#         - hbase_standalone
#         - rabbit
#     ports:
#         - 4242:4242
#     expose:
#         - 4242
#     container_name: tsdb
#     environment:
#         TIMEZONE: Asia/Bangkok
#         HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181
#         HBASE_HOME: /opt/hbase
#     volumes_from:
#         - hbase_standalone
#         - unison_2
#     # volumes:
#     #     - ./opentsdb/dev:/home/dev/opentsdb-dev

#   unison_2:  
#       image: leighmcculloch/unison:latest  
#       environment:  
#           - UNISON_WORKING_DIR=/opt/opentsdb/opentsdb-2.3.0
#       volumes:
#           - /opt/opentsdb/opentsdb-2.3.0
#       ports:  
#           - "5000:5000"