version: '2'
services:
  hbase_standalone:
    build: hbase/
    image: hbase:1.2.4
    ports:
      - 2181:2181
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    # volumes:
        # - /home/mildronize/tmp/hbase:/data/hbase
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181

  tsdb-test:
    build:
      context: ./opentsdb
      dockerfile: Dockerfile.test

    image: opentsdb:2.3-test
    depends_on:
        - hbase_standalone
    ports:
        - 4243:4242
    expose:
        - 4242
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181
        HBASE_HOME: /opt/hbase
    volumes_from:
        - hbase_standalone
    
