version: '2'
services:
  hbase_standalone:
    build: hbase/
    image: hbase:1.2.4
    ports:
      - 2181:2181
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    # volumes:
        # - /home/mildronize/tmp/hbase:/data/hbase
    container_name: hbase
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181

  opentsdb:
    build: opentsdb/
    image: opentsdb
    depends_on:
        - hbase_standalone
    ports:
        - 4242:4242
    container_name: opentsdb
    environment:
        TIMEZONE: Asia/Bangkok
        HBASE_ZOOKEEPER_QUORUM: hbase_standalone:2181
    volumes_from:
        - hbase_standalone
