version: '2'
services:
  hbase_standalone:
    build: hbase/
    image: 'hbase:1.2.6'
    ports:
      - '2181:2181'
      - '16000:16000'
      - '16010:16010'
      - '16201:16201'
      - '16301:16301'
    container_name: hbase
    environment:
      TIMEZONE: Asia/Bangkok
      HBASE_ZOOKEEPER_QUORUM: 'hbase_standalone:2181'
  tsdb:
    build: ./opentsdb
    image: opentsdb
    depends_on:
      - hbase_standalone
    ports:
      - '4242:4242'
    container_name: tsdb
    environment:
      TIMEZONE: Asia/Bangkok
      HBASE_ZOOKEEPER_QUORUM: 'hbase_standalone:2181'
    volumes_from:
      - hbase_standalone
  tsdb-dev:
    build:
      context: ./opentsdb
      dockerfile: Dockerfile.test
    image: 'opentsdb:2.3-test'
    depends_on:
      - hbase_standalone
      - memcached
    ports:
      - '4242:4242'
    expose:
      - 4242
    container_name: tsdb
    environment:
      TIMEZONE: Asia/Bangkok
      HBASE_ZOOKEEPER_QUORUM: 'hbase_standalone:2181'
      HBASE_HOME: /opt/hbase
    volumes_from:
      - hbase_standalone
      - unison

  tsdb-test:
    build:
      context: ./opentsdb
      dockerfile: Dockerfile.test
    image: 'opentsdb:2.3-test'
    depends_on:
      - hbase_standalone
      - memcached
    ports:
      - '4242:4242'
    expose:
      - 4242
    container_name: tsdb
    environment:
      TIMEZONE: Asia/Bangkok
      HBASE_ZOOKEEPER_QUORUM: 'hbase_standalone:2181'
      HBASE_HOME: /opt/hbase
    volumes_from:
      - hbase_standalone
    volumes:
      /opt/opentsdb/opentsdb-2.3.0:/home/mildronize/opentsdb

  memcached:
    image: 'memcached:1.5-alpine'
    container_name: memcached
    ports:
      - '11211:11211'
    command: memcached -vv

  unison:
    image: 'leighmcculloch/unison:latest'
    environment:
      - UNISON_WORKING_DIR=/opt/opentsdb/opentsdb-2.3.0
    volumes:
      - /opt/opentsdb/opentsdb-2.3.0
    ports:
      - '5000:5000'
