version: '2'
services:
  hbase:
    # build: hbase/
    image: hbase-for-opentsdb
    ports:
        - "16010:16010"
        - "2181:2181"
    # volumes:
        # - /home/mildronize/tmp/hbase:/data/hbase
    container_name: hbase
    hostname: hbase.vnet
    networks: ["vnet"]
    environment:
        TIMEZONE: Asia/Bangkok
        ZOOKEEPER_HOST: hbase.vnet:2181

  opentsdb:
    image: opentsdb
    depends_on:
        - hbase
    ports:
        - "4242:4242"
    container_name: opentsdb
    hostname: opentsdb.vnet
    networks: ["vnet"]
    environment:
        TIMEZONE: Asia/Bangkok
        ZOOKEEPER_HOST: hbase.vnet:2181
    volumes_from:
        - hbase

networks:
  vnet:
    external:
      name: vnet
