version: '2'
services:
  hbase:
    # build: hbase/
    image: hbase-for-opentsdb
    ports:
      - 2181:2181
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
    # volumes:
        # - /home/mildronize/tmp/hbase:/data/hbase
    container_name: hbase
    environment:
        TIMEZONE: Asia/Bangkok
        ZOOKEEPER_HOST: hbase:2181

  opentsdb:
    image: opentsdb
    depends_on:
        - hbase
    ports:
        - "4242:4242"
    container_name: opentsdb
    environment:
        TIMEZONE: Asia/Bangkok
        ZOOKEEPER_HOST: hbase:2181
    volumes_from:
        - hbase
